version: "3.9"

services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REBUGIT_API_KEY="<your project api key>"
      - REBUGIT_API_ENDPOINT="<the rebugit tracer api endpoint>"
      - REBUGIT_LOG=ALL
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - MYSQL_DB_HOST=userdb
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_PASSWORD=mysql
      - MYSQL_DB_USER=mysql
      - MYSQL_DB_NAME=mysql
      - PORT=8080
      - AWS_REGION=us-east-1
      - SECRET_NAME=example/mapQuestApikey
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
    depends_on:
      - db
      - userdb

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  userdb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=mysql