version: "3.9"

services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REBUGIT_API_KEY="<your project api key>"
      - REBUGIT_API_ENDPOINT="<the rebugit tracer api endpoint>"
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - PORT=8080
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

#  frontned:
#    build:
#      dockerfile: frontend.Dockerfile
#    ports:
#      - "3000:3000"